export const START_LOADING_MATCHES = 'START_LOADING_MATCHES';
export const SUCCESS_LOADED_MATCHES = 'SUCCESS_LOADED_MATCHES';
export const FAILED_LOADED_MATCHES = 'FAILED_LOADED_MATCHES';

export const CHANGE_ARRAY = 'CHANGE_ARRAY';
export const REMOVE_ITEM_FROM_ARRAY = 'REMOVE_ITEM_FROM_ARRAY';